import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner'
import Card from '../components/card'

// Prerender coffeeStores and prerender with getStaticProps
import coffeeStoresData from '../data/coffee-stores.json'


export async function getStaticProps(context) {

  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: 'fsq3KuOdSnYpgAmQg47Kn+TJzI3dfmyaDbTvErsnDQ8CPAo='
    }
  };

  const response = await fetch('https://api.foursquare.com/v3/places/search?query=coffee&ll=43.65115438290401%2C-79.37832859616533&limit=6', options)

  const data = await response.json();

  // .catch(err => console.error(err));

  return {
    props: {
      coffeeStores: data.results,
    }, // will be passed to the page component as props. We don't have to fetch it as we already have the data
  }
}

export default function Home(props) {

  const handleOnBannerBtnClick = () => {
    console.log('hi banner button');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {/* Mapping through coffeeStores from the getStaticProps */}
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || '/static/coffee-bg.jpeg'}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />
                )
              })}
            </div>
          </>
        )}
      </main>
    </div>
  )
}
